#!/bin/bash

# This script is a wrapper around /usr/bin/vlc
# It disables dpms and passes all arguments unchanged to the
# 'real' vlc

# Note:
# The script does not handle launching several instances of vlc
# concurrently. It is the users responsability to not launch
# more than 1 vlc instance at any time. When 2 instances run
# concurrently, the first one that finishes will turn dpms on again.

dpms() {
    # $1: on or off
    test $1 == on && switch='true' || switch='false'
    xfconf-query -c xfce4-power-manager \
                 -p /xfce4-power-manager/dpms-enabled \
                 -s "$switch"
}

dpms off
# Make sure dpms is enabled again at exit
trap 'dpms on' EXIT
# Pass all arguments on to the 'real' vlc
# Don't uses 'exec' here if you want the 'trap' command to work.
/usr/bin/vlc "$@"
