#!/bin/bash

# Arguments:
#        $1: CHROOT_DEVICE
#        $2: CHROOT_MOUNTPOINT

# And replace the COMMANDS array definition in yje main section of
# this script with the series of commands you want to run in the
# chroot

# e.g. chroot.sh /dev/mapper/VG10-linuxBBQ 

# Is it possible to run more than 1 command in one run?
# YES! By putting the commands in a global array

debug=yes

source chroot_lib

CHROOT_DEVICE="$1"
CHROOT_MOUNTPOINT="$2"

declare -a COMMANDS
# Change the COMMANDS definition to the series of commands you want to run

# -----------------------------------------------------------------------

# Example 1: Install grub to the MBR of your HD and run update-grub
COMMANDS=( \
    'grub-install /dev/sda' \
    'update-grub' \
    )


# Example 2:
#     run apt-get update and apt-get dist-upgrade in a system you chroot into
# COMMANDS=( \
#     'apt-get update' \
#     'apt-get dist-upgrade' \
#     )

# Example 3: install the 'lvm2' package in a system you chroot into
#     and run update-initrams
# COMMANDS=( \
#     'apt-get update' \
#     'apt-get install lvm2' \
#     '/usr/sbin/update-initramfs -u -vvv /initrd.img' \
#     )

# COMMANDS=( \
#     'man ceni' \
#     )


# -----------------------------------------------------------------------

do_chroot C$CHROOT_DEVICE $CHROOT_MOUNTPOINT

