#!/bin/bash
DIMENSIONS=100x70
TOP=700
LEFT=30
INCREMENT=30
LOCAL_COLORTHEME_DIRECTORY=$HOME/.local/share/console-colors

# array of themes: locally installed color themes
declare -a themes
mapfile -t -n 0 themes < <(ls -1 $LOCAL_COLORTHEME_DIRECTORY | shuf)
echo ${themes[@]}

args="$@"

new_instance () {
    instances="$(ps -eF | awk '{print $11}' | grep -E '^/usr/bin/xterm' | wc -l)"
    
    top=$(( TOP + INCREMENT * instances ))
    left=$(( LEFT + INCREMENT * instances ))
    case $instances in
	0) 
	    # standard theme from .Xresources
	    theme=
	    ;;
	*) 
	    # theme from collection of color-themes
	    theme=${themes[(( instances % (( ${#themes[@]} )) ))]}
	    ;;
    esac
    command="/usr/bin/xterm -geometry ${DIMENSIONS}+${top}+${left}"
    options=
    if [[ "$theme" ]]; then
	echo "$theme" >> $LOGFILE
	options="-e 'console-colors s ${theme}"
	if [[ "${args}" ]]; then
	    options="-hold ${options}; ${args}'"
	else
	    options="${options}; ${SHELL}'"
	fi
    else
	if [[ "$args" ]]; then
	    options="-hold -e '${SHELL} -c ${args}'"
	    # else
	    # 	options=
	fi
    fi
    eval "COLORTHEME="$theme" $command $options &"
}
new_instance
