#!/bin/bash

set -e

die() {
    printf '%b\n' >&2 "\033[36m[E] $*\033[0m"
    exit 1
}

warn() {
    printf '%b\n' >&2 "\033[36m[W] $*\033[0m"
}

usage () { cat >&2 <<EOF

Usage: 
zimgur import <image_file_name.(png|jpg)>
or
zimgur upload <image_file_name.(png|jpg)> | xclip
or
zimgur both <image_file_name.(png|jpg)> | xclip

Create an image file by selecting a rectangle or single clicking to
select a window or double clicking to select the full screen.

Creates a thumbnail of the image and uploads both images to the imgur
server.

Ouputs BB code to publish the image on a forum.

EOF
exit 1
}
IMUP=/usr/local/bin/imup.py

check_argument () {
    [[ "$1" ]] || { warn "missing path-to-image argument"; usage; }
    local image="$1"
    local extension=${image##*.}
    case $extension in
        png|jpg)
            :;;
        *)
            warn "file $1 has wrong extension"
            usage
            ;;
    esac
}

do_import () {
    command import -pause 1 "$1"
    if (( $? != 0 )); then die "import $1 failed"; fi
}

do_upload () {
    local image="$1"
    local link_to_image=$($IMUP -i imgur "$image")
    if (( $? != 0 )); then die "upload of $image failed"; fi
    local thumb=${image##*.}-t.${extension}
    command convert $image -resize 96X54 "$thumb"
    if (( $? != 0 )); then die "creating a thumbnail of $image failed"; fi
    local link_to_thumb=$($IMUP -i imgur "$thumb")
    if (( $? != 0 )); then die "uploading the thumbnail image failed"; fi
    printf '[URL=%s][IMG]%s[/IMG][/URL]' "$link_to_image" "$link_to_thumb"
}

(( $# > 0 )) || { warn "missing command"; usage; }
command="$1"
shift
[[ $command =~ '-h|--help' ]] && usage
(( $# > 0 )) || { warn "missing argument"; usage; }
check_argument "$1"
case $command in
    import) 
        printf '%s\n' "import"
        do_import "$1"
        ;;
    upload) 
        printf '%s\n' "upload"
        do_upload "$1"
        ;;
    both)
        printf '%s\n' "both"
        do_import "$1"
        do_upload "$1"
        ;;
    *) 
        warn "unknown command: $command"
        usage
        ;;
esac
